export const Posts = [
	{
		id: 1,
		desc: "I'm working remotly now!",
		photo: '/assets/post/1.jpeg',
		date: '5分前',
		userId: 1,
		like: 20,
		comment: 4,
	},
	{
		id: 2,
		desc: 'I love this place!',
		photo: '/assets/post/2.jpeg',
		date: '2分前',
		userId: 2,
		like: 140,
		comment: 13,
	},
	{
		id: 3,
		desc: 'working hard',
		photo: '/assets/post/3.jpeg',
		date: '10分前',
		userId: 3,
		like: 230,
		comment: 29,
	},
	{
		id: 4,
		photo: '/assets/post/4.jpeg',
		date: '1分前',
		userId: 4,
		like: 10,
		comment: 1,
	},
	{
		id: 5,
		desc: 'Let us take a break',
		photo: '/assets/post/5.jpeg',
		date: '1分前',
		userId: 5,
		like: 100,
		comment: 3,
	},
]
